name: Deploy Vite App to S3 + CloudFront

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps (root)
        run: npm ci

      - name: Create env for production (client/)
        run: |
          mkdir -p client
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> client/.env.production
          
      - name: Show env file (debug)
        run: cat client/.env.production
        
      - name: Build (root script)
        run: npm run build
        env:
           VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Verify API base in bundle
        run: |
          grep -R "api\.flow-ext-block\.site" -n dist/public || (echo "NOT FOUND in bundle"; exit 1)


      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # outDir: dist/public 에 맞춰 업로드
      - name: Upload assets (immutable)
        run: |
          aws s3 sync dist/public s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp dist/public/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
